app:
    resource: '@AppBundle/Controller/'
    type: annotation
#avanzu_admin:
#    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"